
import Stripe from 'stripe';

// Generated by scripts/stripe-sync.js — do not edit manually
const PRICE_IDS = {
    monthly: 'price_1TPn0CC5seLx7yR7QPXo3bUA',
    annual:  'price_1TPn0DC5seLx7yR7XU0C9Dsz',
};

export const onRequestPost = async (context) => {
    const stripe = new Stripe(context.env.STRIPE_SECRET_KEY, {
        apiVersion: '2023-10-16',
        httpClient: Stripe.createFetchHttpClient(),
    });

    let plan;
    try {
        const body = await context.request.json();
        plan = body.plan;
    } catch {
        return new Response(JSON.stringify({ error: 'Invalid request body' }), {
            status: 400,
            headers: { 'Content-Type': 'application/json' },
        });
    }

    const priceId = PRICE_IDS[plan];

    if (!priceId) {
        return new Response(JSON.stringify({ error: 'Invalid plan' }), {
            status: 400,
            headers: { 'Content-Type': 'application/json' },
        });
    }

    try {
        const session = await stripe.checkout.sessions.create({
            line_items: [{ price: priceId, quantity: 1 }],
            mode: 'subscription',
            success_url: `${new URL(context.request.url).origin}/premium/`,
            cancel_url: `${new URL(context.request.url).origin}/unlock/`,
        });

        return new Response(JSON.stringify({ url: session.url }), {
            headers: { 'Content-Type': 'application/json' },
        });
    } catch (err) {
        return new Response(JSON.stringify({ error: err.message }), {
            status: 400,
            headers: { 'Content-Type': 'application/json' },
        });
    }
};
