import os
import requests
import stripe
import json
import datetime
import sys
from dotenv import load_dotenv

sys.path.append(os.path.expanduser("~/.gemini/antigravity/runtime"))
from global_paths import resolve_path

# Load credentials
load_dotenv()

# Configuration
STRIPE_KEY = os.getenv("STRIPE_SECRET_KEY")
POSTMARK_TOKEN = os.getenv("POSTMARK_SERVER_TOKEN")
INSTANTLY_KEY = os.getenv("INSTANTLY_API_KEY")

stripe.api_key = STRIPE_KEY

def get_revenue_metrics():
    """Fetches MRR and Subscriber counts from Stripe."""
    if not STRIPE_KEY: return {"error": "Missing Stripe Key"}
    
    print("📊 Polling Stripe...")
    try:
        # Simplified MRR Calc (Sum of active subscriptions)
        # For production, use Stripe Billing Analytics API or iterate all subs
        subs = stripe.Subscription.list(status='active', limit=100)
        mrr = 0
        active_count = 0
        
        for sub in subs.data:
            active_count += 1
            if sub.items.data:
                price = sub.items.data[0].price
                if price.unit_amount:
                     mrr += price.unit_amount / 100 # Convert cents to dollars

        return {
            "active_subscribers": active_count,
            "estimated_mrr": mrr
        }
    except Exception as e:
        return {"error": str(e)}

def get_email_metrics():
    """Fetches Open/Click rates from Postmark."""
    if not POSTMARK_TOKEN: return {"error": "Missing Postmark Token"}
    
    print("📧 Polling Postmark...")
    try:
        headers = {"X-Postmark-Server-Token": POSTMARK_TOKEN, "Accept": "application/json"}
        # Get Outbound Overview
        # Docs: https://postmarkapp.com/developer/api/stats-api
        today = datetime.date.today()
        first_of_month = today.replace(day=1)
        
        url = f"https://api.postmarkapp.com/stats/outbound?fromdate={first_of_month}&todate={today}"
        r = requests.get(url, headers=headers)
        r.raise_for_status()
        data = r.json()
        
        return {
            "sent": data.get("Sent", 0),
            "opened": data.get("Opens", 0),
            "unique_opened": data.get("UniqueOpens", 0),
            "clicked": data.get("Clicks", 0)
        }
    except Exception as e:
        return {"error": str(e)}

def get_outreach_metrics():
    """Fetches Cold Lead stats from Instantly."""
    if not INSTANTLY_KEY: return {"error": "Missing Instantly Key"}
    
    print("❄️ Polling Instantly...")
    try:
        # Note: Instantly API analytics endpoints vary by plan.
        # We will try to fetch campaign summaries if available, or just lead counts.
        # Fallback: List campaigns and sum active leads.
        
        headers = {"Authorization": f"Bearer {INSTANTLY_KEY}"}
        url = "https://api.instantly.ai/api/v1/campaign/list"
        
        r = requests.get(url, headers=headers)
        r.raise_for_status()
        campaigns = r.json()
        
        total_leads = 0
        total_contacted = 0
        
        # This structure depends on Instantly's exact JSON response
        for c in campaigns:
            # Check if campaign object has stats
            # This is a best-guess schema based on typical API patterns
            # We'll just count campaigns for now to be safe
            pass
            
        return {
            "active_campaigns": len(campaigns),
            "note": "Detailed lead stats require Campaign ID iteration."
        }
    except Exception as e:
        return {"error": str(e)}

def generate_report():
    print("--- 🧠 Generating Weekly Intelligence Report ---")
    
    rev = get_revenue_metrics()
    email = get_email_metrics()
    growth = get_outreach_metrics()
    
    report = f"""
# 🧠 Weekly Intelligence Brief
**Date:** {datetime.date.today()}

## 1. Revenue (Stripe)
*   **Active Subscribers:** {rev.get('active_subscribers', 'N/A')}
*   **Estimated MRR:** ${rev.get('estimated_mrr', '0.00')}

## 2. Engagement (Postmark - MTD)
*   **Emails Sent:** {email.get('sent', 0)}
*   **Unique Opens:** {email.get('unique_opened', 0)}
*   **Clicks:** {email.get('clicked', 0)}

## 3. Growth (Instantly)
*   **Active Campaigns:** {growth.get('active_campaigns', 0)}
*   *{growth.get('note', '')}*

---------------------------------------------
*Generated by the Lean Stack Intelligence Layer*
    """
    
    # Ensure reports dir exists via python logic (or assume simple write)
    # We'll just print to stdout for the MVP, effectively the "Dashboard"
    print(report)
    
    # Also save to file
    today_str = datetime.date.today().strftime("%Y-%m-%d")
    filename = resolve_path(f"{{ANTIGRAVITY_DATA_DIR}}/micro-site/agent-site/docs/reports/{today_str}_brief.md")
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    with open(filename, "w") as f:
        f.write(report)
    print(f"✅ Report saved to {filename}")

if __name__ == "__main__":
    generate_report()
